### ISSUE TITLE
Discussion: Is this OP?: The "Disarm" ability of the "Unarmed" skill in mcMMO

### ISSUE THREAD

**Issue by MilesBHuff** [SettleScape/server#131]
Is Disarm so OP/broken that it needs to be disabled?
@drakedebaun

**Comment by drakedebaun** [comment]
I don't think its broken, for the following reasons:
it's a chance on hit, not on damage taken
after around 15 hours of the highest theoretical training speed possible, I am sitting at 11% chance to disarm (level 36)
also, I'm sitting at 36% chance to ignore an incoming disarm (look up iron grip, gives chance to ignore disarms)
so yeah, its powerful, but it takes a lot of time investment and there are in-game counters to it that already exist

**Comment by MilesBHuff** [comment]
Got it.  I'm worried though about people losing super expensive items to lava, the void, etc.
If there were a way to move the item to the player's inventory rather than dropping it, I would be 100% for it.

**Comment by MilesBHuff** [comment]
Closing in favor of #138.
