### ISSUE TITLE
Essentials `/repair` and mcMMO `/repair` conflict

### ISSUE THREAD

**Issue by drakedebaun** [SettleScape/server#93]
the `/repair` command properly brings up the mcmmo repair skill card, but attempting to use it again gives you a message saying you must wait to use it again.  there is a conflict between mcmmo's `/repair` command and essentials `/repair` command

**Comment by MilesBHuff** [comment]
Oof.  Thanks for letting me know.
There doesn't appear to be a clear, easy solution for this.

Options:

1. Rename the skill in mcMMO.
2. Try to do something fancy with aliases.

    a. Maybe prefix all mcMMO commands?
    b. Maybe alias Essentials `/repair` to `/mend`?

3. Remove the Essentials `/repair` perk from Pathfinder's perks.
4. Something else?

I'll have to weigh the pros and cons of each option, and see which work and which do not.

**Comment by MilesBHuff** [comment]
"Resolved" by removing the `repair` perk.  :\ 
Commit 691150eb76e6c6fd6825a0f286224175f9a574bf.
