### ISSUE TITLE
speed up fishing xp gain?

### ISSUE THREAD

**Issue by drakedebaun** [SettleScape/server#97]
fished for 2 and a half hours last night, got 4 levels out of it- from 29 to 33.  this seems really really slow.  any way we could speed it up to make it more in line with other skills?

**Comment by MilesBHuff** [comment]
After some math, I found that the current exp rate for fishing, at the speed you gave above (which, knowing you, is breakneck), is 150 hours to get to level 100.
At 3x current rates, it's 50 hours;  at 4x current rates, it's 37.5.

**Comment by MilesBHuff** [comment]
After discussion with @drakedebaun, we decided on an intermediate value of 3.5.

**Comment by MilesBHuff** [comment]
Completed in 017ad75.
