### ISSUE TITLE
Fishing's 'Magic Hunter' perk

### ISSUE THREAD

**Issue by drakedebaun** [SettleScape/server#98]
the fishing perk 'Magic Hunter' can give you 2+ enchantments on an item that are normally mutually exclusive.  this allows for fortune III + silk touch picks, which is harmful for the server's economy balance.  disabling the perk should be enough, as enchanted items can already be fished up without it!

**Comment by MilesBHuff** [comment]
Good catch!  Good points as well -- it doesn't seem like a worthwhile perk.  I'll strip it out.

**Comment by MilesBHuff** [comment]
Completed in d4c49413d1177c68bb5c3a0e47bfb4444d2f4e2b.
